---
title: Application parkings
subtitle: Analyse des parkings hors voirie
author: Yohann Mansiaux
date: '2021-10-26'
slug: apps-applications-parkings
tags: ["Applications", "Mobilités"]
published: true
resume_court: pkg
---

Cette application propose d'analyser les données d'occupation des parkings hors voirie de Bordeaux Métropole.

Ces données sont présentes sur le portail [open data de Bordeaux Métropole](https://opendata.bordeaux-metropole.fr/explore/dataset/st_park_p/information/).

Cet outil permet d'étudier : 

- les taux d'occupation des parkings sur 1 période d'intérêt (1 journée, 1 semaine, 1 mois ou 1 année), pour 4 grands secteurs (l'hypercentre de Bordeaux, le centre de Bordeaux, la périphérie de Bordeaux et les parcs relais). Une sélection personnalisée de parkings peut également réalisée.

- les niveaux de saturation : quels parkings sont très occupés, au moins x heures dans une journée et au moins x jours dans une semaine ?

Cette application m'a permis d'expérimenter pour la première fois l'utilisation du package _{R6}_ pour créer des objets "Parkings" avec leur caractéristiques propres (identifiant, données associées ...).

J'ai également testé l'utilisation du package _memoise}_ pour mettre en cache des résultats d'appels à des fonctions. En effet dans cet outil l'utilisateur peut potentiellement réaliser plusieurs la même requête (date identique sur un jeu de parkings identiques). Il était intéressant de mettre en cache des résultats de requêtes déjà réalisées afin de renvoyer les résultats plus rapidement !

Le code source est présent <a href="https://github.com/ymansiaux/occupationparkingsapp" target="_blank" rel="noopener noreferrer" class="button">ici</a>.

<p><a href="https://rstudio-connect.bordeaux-it.fr/occupationparkingsapp/" target="_blank" rel="noopener noreferrer" class="button">Accéder à l'application</a></p>
