baseurl: /
relativeurls: true
DefaultContentLanguage: fr
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
title: Bienvenue !
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  comments: yes
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/LogoDataLab.ico
  logo: img/YM.jpg
  mainSections:
    - post
    - posts
  readingTime: yes
  rss: yes
  showRelatedPosts: yes
  socialShare: false
  subtitle: Qui suis-je ?
  useHLJS: yes
  wordCount: yes
Author:
  email: y.mansiaux@bordeaux-metropole.fr
  github: github.com/ymansiaux
  gitlab: https://gitlab.com/bordeaux-metropole-public
  name: Yohann Mansiaux
menu:
  main:
    - name: Accueil
      url: ''
      weight: 1
    - name: Tous les contenus
      url: blog/
      weight: 2
    - name: A propos
      url: page/about/
      weight: 3
    - name: Mots clés
      url: tags
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
