---
title: Bot twitter
subtitle: Bot twitter sur l'ouverture du pont Chaban Delmas à Bordeaux
author: Yohann Mansiaux
date: '2022-07-19'
slug: tools-bot-twitter
tags: ["Outils", "Bot"]
published: true
---

Mini projet "jouet" pour tester l'implémentation d'un bot twitter.

Tous les matins, ce programme va publier l'état d'ouverture du pont Chaban Delmas à Bordeaux et les fermetures éventuelles dans la journée.

Les données d'ouverture / fermeture prévisionnelles proviennent du [portail open data de Bordeaux Métropole](https://opendata.bordeaux-metropole.fr/explore/dataset/previsions_pont_chaban/information/).

La publication des tweets est réalisée via le package _{rtweet}_.

Pour réaliser ce programme j'ai suivi le tuto super complet du créateur du bot [londonmapbot](https://github.com/matt-dray/londonmapbot).

Pour utiliser _{rtweet}_, il est nécessaire d'avoir un compte développeur sur twitter de niveau Elevated. Tout est bien expliqué dans le tuto, et les liens vers la doc Twitter y sont présents.

Les ressources suivantes m'ont également été utiles pour tout bien configurer :

* [Documentation de rtweet](https://docs.ropensci.org/rtweet/reference/index.html)

* [Article de R bloggers](https://www.r-bloggers.com/2022/01/tips-for-building-a-twitter-bot-with-r-and-github-actions/?utm_source=phpList&utm_medium=email&utm_campaign=R-bloggers-daily&utm_content=HTML)


Il s'agissait d'un premier test assez simple de l'utilisation de _{rtweet}_, avant d'envisager d'autres applications plus tard, peut-être plus utiles ;-)

Les tweets sont publiés <a href="https://twitter.com/ymansiauxdata" target="_blank" rel="noopener noreferrer" class="button">ici</a>.

Le code source est présent <a href="https://github.com/ymansiaux/bot_chaban" target="_blank" rel="noopener noreferrer" class="button">ici</a>.


